---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mc3-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube-data/mc3/data"
