apiVersion: v1
kind: Service
metadata:
  name: mcserver
  labels:
    name: mcserver
spec:
  type: ClusterIP
  clusterIP: 10.4.1.12
  selector:
    name: mcserver
    app: mcserver
  ports:
  - name: mcserver
    port: 25565
    protocol: TCP
    targetPort: 25565
